### ISSUE TITLE
PSR-4

### ISSUE THREAD

**Issue by KennedyTedesco** [php-brasil/shopping#2]
Olá, estou de intruso aqui. Tenho acompanhado as discussões e o andamento do projeto. Muito legal, parabéns! =)

O que acham de usar PSR-4?

Então, ao invés de termos um caminho físico desse:

``` php
src/PHPBr/Shopping
```

Manteríamos o **namespace**, só que mapeado a um caminho arbitrário, no caso:

``` php
src
```

Sei que o projeto é didático. É apenas uma sugestão mesmo. Sintam-se livres pra fechar a issue. :wink:

**Comment by lcobucci** [comment]
Eu acho bacana @KennedyTedesco, que tal você mandar um PR?

**Comment by KennedyTedesco** [comment]
@lcobucci Combinado! Vou fazer isso hoje a noite.

:beers:

**Comment by lcobucci** [comment]
Awesome!

**Comment by KennedyTedesco** [comment]
Nota: PR enviado https://github.com/php-brasil/shopping/pull/3

Fechando a Issue. :beer:
